# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a65fdd0d3652fcc9399237ef088157b5a95e62e73622b90001531e6e298d741c2f061eee37aa98fbbac06996c467137b3e560dff7b4889c14d4b38e186234c2

test:
  secret_key_base: 4e4b45ea73ea18a3d1b47568e3cd9e73d5a6730ab3575c044e5d5413656a77b14c3979b00cd2ed9e40ede8f35e1c0ac0dbe8b34c2ed94f38dc68473de1c288cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
